unbind r
bind r source-file ~/.tmux.conf

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

#Sensible Options

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Upgrade $TERM
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

#Set leader key
set -g prefix C-a

set -g mouse on

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# List of plugins
set -g @tpm_plugins '
    tmux-plugins/tpm
    tmux-plugins/tmux-sensible
    tmux-plugins/tmux-resurrect
    tmux-plugins/tmux-continuum
    tmux-plugins/tmux-yank
    27medkamal/tmux-session-wizard
'


set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

unbind t
set -g @session-wizard 't'

# Styles

set -g status-position top
set -wg automatic-rename on

# Catpuccin Options
set -g @catppuccin_flavour 'mocha'
run ~/.tmux/plugins/catppuccin/catppuccin.tmux

# Status styles
set -g @catppuccin_window_status_enable "yes"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator " "
set -g @catpuccin_status_fill "all"

# Status elements
set -gF status-right "#{@catppuccin_status_directory}"
# set -agF status-right "#{@catppuccin_status_battery}" # for some reason the battery plugin does not work :/
# set -agF status-right "#{?#{e|>=:10,#{battery_percentage}},#{#[bg=#{@thm_red},fg=#{@thm_mantle}]},#{#[bg=#{@thm_mantle},fg=#{@thm_pink}]}} #{battery_icon} #{battery_percentage} "

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
